### ISSUE TITLE
Visible plugin page error

### ISSUE THREAD

**Issue by DamianHerrington** [PinchOfCode/woocommerce-filter-search#3]
I'm using WordPress 4.1.3 and when I search a site I'm developing with your plugin activated I see the error at the top of my screen..."Notice: like_escape is deprecated since version 4.0! Use wpdb::esc_like() instead. in /path/folders/wp-includes/functions.php on line 3378" Are you releasing any updates soon that would stop this from happening? Or could tell me any code that needs replacing? I've also attached the image too. Thanks.
 
![plugin-error](https://cloud.githubusercontent.com/assets/10584265/7345680/01599ffe-eccf-11e4-86bc-a16a756d72bc.jpg)

**Comment by SiR-DanieL** [comment]
Fixed

**Comment by DamianHerrington** [comment]
Thanks!
